
version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.8
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres
    restart: always

  # reminder-api:
  #   container_name: reminder-api
  #   image: reminder-api
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres
  #   restart: always
    

networks:
  postgres:
    driver: bridge